// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDbvvQVAThLQ3zczZF57EO90lCt4LxxSE',
    appId: '1:1020525855072:web:d42774db7b69a16d795e05',
    messagingSenderId: '1020525855072',
    projectId: 'facilityapp-446601',
    authDomain: 'facilityapp-446601.firebaseapp.com',
    storageBucket: 'facilityapp-446601.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFSh4jEN59YNuQRMslglzJwwZlmvsaw-k',
    appId: '1:1020525855072:android:1b33e3ed7b622e38795e05',
    messagingSenderId: '1020525855072',
    projectId: 'facilityapp-446601',
    storageBucket: 'facilityapp-446601.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLnpRedT_ddOnF1xWzubWQV0j0E-g_9s',
    appId: '1:1020525855072:ios:85c505f2568783d8795e05',
    messagingSenderId: '1020525855072',
    projectId: 'facilityapp-446601',
    storageBucket: 'facilityapp-446601.firebasestorage.app',
    androidClientId: '1020525855072-e7ftvb935oj753qc6g5p27mbr64qv9tf.apps.googleusercontent.com',
    iosClientId: '1020525855072-ds92mk618coofs7qd9p84t9vph8v8014.apps.googleusercontent.com',
    iosBundleId: 'com.example.facilityflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLnpRedT_ddOnF1xWzubWQV0j0E-g_9s',
    appId: '1:1020525855072:ios:85c505f2568783d8795e05',
    messagingSenderId: '1020525855072',
    projectId: 'facilityapp-446601',
    storageBucket: 'facilityapp-446601.firebasestorage.app',
    androidClientId: '1020525855072-e7ftvb935oj753qc6g5p27mbr64qv9tf.apps.googleusercontent.com',
    iosClientId: '1020525855072-ds92mk618coofs7qd9p84t9vph8v8014.apps.googleusercontent.com',
    iosBundleId: 'com.example.facilityflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDbvvQVAThLQ3zczZF57EO90lCt4LxxSE',
    appId: '1:1020525855072:web:5ceba900964804d9795e05',
    messagingSenderId: '1020525855072',
    projectId: 'facilityapp-446601',
    authDomain: 'facilityapp-446601.firebaseapp.com',
    storageBucket: 'facilityapp-446601.firebasestorage.app',
  );
}
